source "https://rubygems.org"

# Specify your gem's dependencies in redix.gemspec
gemspec

gem 'daemons'
gem 'minitest'
# gem 'rbs'
gem 'rake'
gem 'redis'
gem 'rubocop'
gem 'rubocop-minitest'
gem 'rubocop-performance'
